version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - bodyclose
    - errorlint
    - misspell
    - nilerr
    - unconvert
    - unparam

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  goimports:
    local-prefixes: github.com/juev/hledger-lsp

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
